### PR TITLE
Add NPM "start"

### PR DESCRIPTION
**Pull request by streetlight**
In case you wanted to run the package completely through npm. Very minor but hope it helps! Feel free to close if not wanted.

### CODE REVIEW

**Comment by kumar303** [comment]
Hi. Thanks for the patch! We use ``grunt start`` to start the server (executing ``main.js`` doesn't do anything). Can you update the patch for that? I think it should be ``"start": "node -e \"require('grunt').cli()\" start"`` but try it out to see what happens.

**Comment by streetlight** [comment]
@kumar303 Will update and test! Thanks for the note :smile:

**Comment by streetlight** [comment]
@kumar303 Works perfectly -- thanks for the tip!

**Comment by kumar303** [comment]
Thanks for the quick follow up

**Pull request merged**
